const colors = {
  light: {
    text: "#171717",
    tint: "#cf152d",
    background: "#ffffff",
    foreground: "#171717",
    card: "#ffffff",
    cardForeground: "#171717",
    primary: "#cf152d",
    primaryForeground: "#ffffff",
    secondary: "#38683D",
    secondaryForeground: "#ffffff",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#171717",
    destructive: "#f03c3c",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#fafafa",
    tint: "#cf152d",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#161616",
    cardForeground: "#fafafa",
    primary: "#cf152d",
    primaryForeground: "#ffffff",
    secondary: "#4a8a52",
    secondaryForeground: "#ffffff",
    muted: "#1c1c1c",
    mutedForeground: "#a3a3a3",
    accent: "#222222",
    accentForeground: "#fafafa",
    destructive: "#f03c3c",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  radius: 6,
};

export default colors;
