import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import clubsRouter from "./clubs";
import eventsRouter from "./events";
import ridersRouter from "./riders";
import registrationsRouter from "./registrations";
import checkinsRouter from "./checkins";
import rfidRouter from "./rfid";
import motosRouter from "./motos";
import resultsRouter from "./results";
import seriesRouter from "./series";
import dashboardRouter from "./dashboard";
import timingRouter from "./timing";
import usersRouter from "./users";
import stripeConnectRouter from "./stripe-connect";
import riderPortalRouter from "./rider-portal";
import videoRouter from "./video";
import storageRouter from "./storage";
import compCodesRouter from "./comp-codes";
import pointsTablesRouter from "./points-tables";
import aiRouter from "./ai";
import practiceRouter from "./practice";
import exportRouter from "./export";
import syncRouter from "./sync";
import offlineRouter from "./offline";
import discountCategoriesRouter from "./discount-categories";
import discountCodesRouter from "./discount-codes";
import teamRouter from "./team";
import clubSettingsRouter from "./club-settings";
import anthropicRouter from "./anthropic/index";
import configRouter from "./config";
import notificationsRouter from "./notifications";
import desktopSyncRouter from "./desktop-sync";
import tracksRouter from "./tracks";
import enduroTimeChecksRouter from "./enduro-time-checks";
import readersRouter from "./readers";
import eventReaderAssignmentsRouter from "./event-reader-assignments";
import readerIngestRouter from "./reader-ingest";

const router: IRouter = Router();

router.use(timingRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(clubsRouter);
router.use(eventsRouter);
router.use(ridersRouter);
router.use(registrationsRouter);
router.use(checkinsRouter);
router.use(rfidRouter);
router.use(motosRouter);
router.use(resultsRouter);
router.use(seriesRouter);
router.use(dashboardRouter);
router.use(usersRouter);
router.use(stripeConnectRouter);
router.use(riderPortalRouter);
router.use(videoRouter);
router.use(storageRouter);
router.use(compCodesRouter);
router.use(pointsTablesRouter);
router.use(aiRouter);
router.use(practiceRouter);
router.use(exportRouter);
router.use(syncRouter);
router.use(offlineRouter);
router.use(discountCategoriesRouter);
router.use(discountCodesRouter);
router.use(teamRouter);
router.use(clubSettingsRouter);
router.use(anthropicRouter);
router.use(notificationsRouter);
router.use(desktopSyncRouter);
router.use(configRouter);
router.use(tracksRouter);
router.use(enduroTimeChecksRouter);
router.use(readersRouter);
router.use(eventReaderAssignmentsRouter);
router.use(readerIngestRouter);

export default router;
