name: Submit existing iOS build

defaults:
  tools:
    node: "20.19.4"
    pnpm: "10.26.1"

jobs:
  submit_ios:
    name: Submit iOS build to TestFlight
    type: testflight
    defaults:
      run:
        working_directory: ./artifacts/rider-app
    env:
      EXPO_DEBUG: "1"
    params:
      build_id: 10a6b622-37e8-41a7-9e5b-543478807fb6